version: '3.8'

services:
  app:
    build: .
    container_name: lamp_app_container
    ports:
      - "80:80"
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_NAME=$DB_NAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
    volumes:
      - ./php:/var/www/html/php
    restart: always
    
