version: "3.8"

services:
  app:
    build: .
    container_name: lamp-app
    restart: always
    ports:
      - "8082:80"
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - phpmyadmin  
    environment:
      - MYSQL_HOST=172.19.0.1 # Connect to local MySQL
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    env_file:
      - .env
    environment:
      - PMA_HOST=host.docker.internal  # Connect to local MySQL
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
